### ISSUE TITLE
Turning today time in lobby

### ISSUE THREAD

**Issue by bluefutureMC** [stefvanschie/buildinggame#26]
Every time I am finishing a round of bg I am going to the lobby and I see that it turned to day time there but everybody that woesen't in the game see it as normal.
I need to relog to fix that.

**Comment by stefvanschie** [comment]
Which spigot/craftbukkit version are you using?

**Comment by bluefutureMC** [comment]
Spigot 1.10

**Comment by stefvanschie** [comment]
I see, I will fix it in the next version.

**Comment by bluefutureMC** [comment]
thx for the support :)

**Comment by stefvanschie** [comment]
Fixed in version 3.0.3

**Comment by bluefutureMC** [comment]
Sorry but the problem is still there and there is another problem that
players that are not op some times turning to gm 0,
i think it is because the timer of the game is displayed in there xp and
you can see your xp bar only when your gm 0/2.

**Comment by stefvanschie** [comment]
Are you sure you're using version 3.0.3? For the gamemode make sure the world's gamemode is set to creative.

**Comment by bluefutureMC** [comment]
I'm sure, do i need to reset my building games config files?

**Comment by stefvanschie** [comment]
No, new settings will automatically be merged into your current files.

**Comment by bluefutureMC** [comment]
you see i mean that the main lobby is turning to day and not the building
game lobby.

**Comment by stefvanschie** [comment]
The players are teleported from the main lobby to the building game lobby right? Cause how would they be able to see the main lobby when they are teleported to the building game lobby?

**Comment by bluefutureMC** [comment]
If you mean the server main lobby yes, if you mean the plugin's main lobby
then no the plugin's main lobby is the arena lobby.

How do i set a world gamemode?

**Comment by stefvanschie** [comment]
I see, the time change when you join a game was requested by someone, but I can make an option to turn that off.

Assuming you use Multiverse for your worlds, you can change the world's gamemode like this: _/mv modify set diff <difficulty> [world]_

**Comment by stefvanschie** [comment]
Added an option to disable this in version 3.1.1.
